name: Build AOwake (Windows)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyautogui

    - name: Build executable
      run: |
        pyinstaller --noconfirm --windowed --onefile --icon=icon.ico main.py

    - name: Upload executable
      uses: actions/upload-artifact@v3.1.2
      with:
        name: AOwake.exe
        path: dist/AOwake.exe
