name: Build AOwake (Cross-Platform)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyautogui

      - name: Build executable
        run: |
          pyinstaller --noconfirm --windowed --onefile --icon=icon.ico main.py

      - name: Upload executable
        uses: actions/upload-artifact@v3.1.2
        with:
          name: AOwake-Windows.exe
          path: dist/AOwake.exe

  build-macos:
    name: Build on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyautogui

      - name: Build executable
        run: |
          pyinstaller --noconfirm --windowed --onefile --icon=icon.icns main.py

      - name: Upload executable
        uses: actions/upload-artifact@v3.1.2
        with:
          name: AOwake-macOS
          path: dist/AOwake

  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyautogui

      - name: Build executable
        run: |
          pyinstaller --noconfirm --windowed --onefile main.py

      - name: Upload executable
        uses: actions/upload-artifact@v3.1.2
        with:
          name: AOwake-Linux
          path: dist/AOwake
